# Generated by Django 4.2 on 2023-05-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MapZone",
        ),
    ]
