# Generated by Django 4.2 on 2023-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_delete_mapzone"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("Polygon", models.TextField(max_length=1000)),
            ],
        ),
    ]
