# Generated by Django 4.2 on 2023-05-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_mapzone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZonePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("user_type", models.CharField(max_length=255)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.zone"
                    ),
                ),
            ],
        ),
    ]
